spring:
  application:
    name: order

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql:///springboot_03?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true

mybatis:
  type-aliases-package: com.imooc.order.po
  config-location: classpath:mybatis/myBatisConfig.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
env:
  dev5
